version: '2'
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /var/www/static
    volumes_from:
      - web
  web:
    # restart: always
    build: ./backend
    environment:
      - DEBUG=1
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/code
    ports:
     - "8000"
    depends_on:
     - db
     - mailserver
  db:
    restart: always
    image: postgres
    ports:
      "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  mailserver:
    image: python:3.6
    command: python -m smtpd -n -c DebuggingServer 0.0.0.0:1025
    ports:
      - "1025:1025"
