version: '2'
services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    volumes:
      - static-files:/var/app/dist
    depends_on:
      - web
      - vue
  web:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    env_file:
      - .env
    command: bash bootstrap-prod.sh
    volumes:
      - /var/app/django/static
    depends_on:
     - db
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    command: npm run build
    volumes:
      - static-files:/var/app/dist
volumes:
  pgdata:
    driver: local
  static-files:
    driver: local
