version: '2'
services:
  web:
    restart: always
    build: ./backend
    environment:
      - DEBUG=1
    command: bash bootstrap.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailserver
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
  mailserver:
    image: python:3.6
    command: python -m smtpd -n -c DebuggingServer 0.0.0.0:1025
    ports:
      - "1025:1025"
  vue:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "8080:8080"
    depends_on:
      - web
volumes:
  pgdata:
    driver: local
