version: '2'
services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    volumes:
      - static-files:/var/app/dist
    depends_on:
      - web
      - vue
    networks:
      - linky_net
      - outside
  web:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    env_file:
      - .env
    command: bash bootstrap-prod.sh
    volumes:
      - /var/app/django/static
    ports:
     - "8000:8000"
    depends_on:
     - db
    networks:
      - linky_net
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - linky_net
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    command: npm run build
    volumes:
      - static-files:/var/app/dist
    networks:
      - linky_net
volumes:
  pgdata:
    driver: local
  static-files:
    driver: local

networks:
  linky_net:
    internal: true
  outside:
