FROM python:3.6
ENV PYTHONUNBUFFERD 1

RUN apt-get update
RUN apt-get install netcat -y

RUN mkdir -p /var/app
WORKDIR /var/app

COPY requirements.txt /var/app/
RUN pip3 install -r requirements.txt

COPY . /var/app/
